feature: adapt library to Discord.js v14 and correct typos
HunteRoi/discord-logger pull request #3
Opened 2022-09-19 15:02 UTC by DrakeXorn

2022-09-19 15:13 UTC, HunteRoi commented
Can you update and run the example as well as the existing unit tests please?

2022-09-19 15:23 UTC, DrakeXorn commented
Shoot, didn't see them. Fixing that right away.

2022-09-22 23:50 UTC, HunteRoi requested changes

2022-09-22 23:50 UTC, HunteRoi commented on tests/_global.ts
> +    [`on_${event}`]: () => void 0,
should be undefined, right?
```suggestion
    [`on_${event}`]: () => undefined,
```

2022-09-22 23:51 UTC, HunteRoi approved these changes

2022-09-22 23:51 UTC, merged